"""initial_dominion

Revision ID: 6750b4f56b86
Revises: 
Create Date: 2026-03-14 17:25:59.041079+03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6750b4f56b86'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_messages_group_created', table_name='chat_messages')
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('master', 'director', 'admin', 'convoy_head', 'manager', name='user_role'),
               server_default=None,
               existing_nullable=True)
    op.create_foreign_key(None, 'users', 'vehicles', ['current_vehicle_id'], ['id'])
    op.create_foreign_key(None, 'vehicles', 'rental_tariffs', ['tariff_id'], ['id'])
    op.create_foreign_key(None, 'vehicles', 'partners', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'vehicles', 'users', ['current_driver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('master', 'director', 'admin', 'convoy_head', 'manager', name='user_role'),
               server_default=sa.text("'manager'::user_role"),
               existing_nullable=True)
    op.create_index('ix_chat_messages_group_created', 'chat_messages', ['group_name', sa.text('created_at DESC')], unique=False)
    # ### end Alembic commands ###
